version: '3'

services: 
  backend_thealfastore:
    container_name: backend_thealfastore
    image: backend
    build: 
      context: .
    ports:
      - "3000:3000"
    environment: 
      - DB_HOST=54.156.167.104
      - DB_NAME=db_thealfastore
      - DB_PASSWORD=password
      - DB_USER=postgres
    depends_on: 
      - node_db
  db_thealfastore: 
    container_name: db_thealfastore
    image: postgres
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_thealfastore
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}
